test_that("make_function_target generates function and result targets", {
  # Function with args
  result <- make_function_target("my_func", list(x = NULL, y = NULL))
  expect_length(result, 2)
  expect_equal(result[1], "  tar_target(.fn_my_func, my_func)")
  expect_equal(result[2], "  tar_target(my_func, .fn_my_func(x, y))")

  # Function with no args
  result <- make_function_target("no_args", list())
  expect_length(result, 2)
  expect_equal(result[1], "  tar_target(.fn_no_args, no_args)")
  expect_equal(result[2], "  tar_target(no_args, .fn_no_args())")
})

test_that("make_constant_target generates correct output", {
  result <- make_constant_target("my_const")
  expect_equal(result, "  tar_target(my_const, my_const)")
})

test_that("generate_targets creates output file", {
  tmp_dir <- withr::local_tempdir()

  # Create R/auto directory with a file
  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "my_data <- mtcars",
      "analyze <- function(my_data) summary(my_data)"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  # Create targets directory
  dir.create(file.path(tmp_dir, "targets"))

  # Generate targets
  generate_targets(path = tmp_dir)

  # Check output file exists
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_true(file.exists(output_file))

  # Check content
  content <- readLines(output_file)
  expect_true(any(grepl("AUTOGENERATED", content)))
  expect_true(any(grepl("tar_target\\(\\.fn_analyze", content)))
  expect_true(any(grepl("tar_target\\(analyze,", content)))
  expect_true(any(grepl("tar_target\\(my_data", content)))
})

test_that("generate_targets with write=FALSE returns lines without writing", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines("x <- 1", file.path(auto_dir, "test.R"))

  result <- generate_targets(path = tmp_dir, write = FALSE)

  expect_type(result, "character")
  expect_true(any(grepl("tar_target", result)))

  # File should not exist
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_false(file.exists(output_file))
})

test_that("function targets create .fn_ prefix for function object tracking", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "data <- 1:10",
      "process <- function(data) data * 2"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # Should have .fn_ prefix for function
  expect_true(any(grepl("tar_target\\(\\.fn_process,", result)))

  # Result target should call .fn_ version
  expect_true(any(grepl("tar_target\\(process, \\.fn_process\\(data\\)\\)", result)))

  # Constants should not have .fn_ prefix
  expect_true(any(grepl("tar_target\\(data, data\\)", result)))
  expect_false(any(grepl("\\.fn_data", result)))
})

test_that("constants evaluate their value directly for change detection", {
  # Constants don't need _fn_ pattern because tar_target(const, const)
  # evaluates to the actual value, which targets hashes.
  # If the constant's value changes, the hash changes and target is invalidated.
  result <- make_constant_target("params")
  expect_equal(result, "  tar_target(params, params)")

  # This is different from functions where the body is encapsulated
  # and not visible in the call expression
})

test_that("file targets are detected by _file suffix", {
  expect_true(is_file_target("raw_data_file"))
  expect_true(is_file_target("output_file"))
  expect_false(is_file_target("data"))
  expect_false(is_file_target("threshold"))
})

test_that("make_file_target adds format = 'file'", {
  result <- make_file_target("raw_data_file")
  expect_equal(result, "  tar_target(raw_data_file, raw_data_file, format = \"file\")")
})

test_that("function targets with _file suffix get format = 'file'", {
  # Function returning a file path should have format = "file" on result target
  result <- make_function_target("output_file", list(data = NULL))
  expect_length(result, 2)
  expect_equal(result[1], "  tar_target(.fn_output_file, output_file)")
  expect_equal(result[2], "  tar_target(output_file, .fn_output_file(data), format = \"file\")")
})

test_that("generate_targets handles file targets for constants and functions", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "raw_data_file <- \"data/input.csv\"",
      "threshold <- 0.05",
      "output_file <- function(data) {",
      "  write.csv(data, \"output.csv\")",
      "  \"output.csv\"",
      "}",
      "process <- function(raw_data_file) read.csv(raw_data_file)"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # Constant file target
  expect_true(any(grepl('tar_target\\(raw_data_file, raw_data_file, format = "file"\\)', result)))

  # Regular constant (no format)
  expect_true(any(grepl('tar_target\\(threshold, threshold\\)', result)))

  # Function file target (result has format = "file")
  expect_true(any(grepl('tar_target\\(\\.fn_output_file, output_file\\)', result)))
  expect_true(any(grepl('tar_target\\(output_file, \\.fn_output_file\\(data\\), format = "file"\\)', result)))

  # Regular function (no format)
  expect_true(any(grepl('tar_target\\(\\.fn_process, process\\)', result)))
  expect_true(any(grepl('tar_target\\(process, \\.fn_process\\(raw_data_file\\)\\)', result)))
})
