test_that("make_function_target generates correct output", {
  # Function with args
  result <- make_function_target("my_func", list(x = NULL, y = NULL))
  expect_equal(result, "  tar_target(my_func, my_func(x, y))")

  # Function with no args
  result <- make_function_target("no_args", list())
  expect_equal(result, "  tar_target(no_args, no_args())")
})

test_that("make_constant_target generates correct output", {
  result <- make_constant_target("my_const")
  expect_equal(result, "  tar_target(my_const, my_const)")
})

test_that("generate_targets creates output file", {
  tmp_dir <- withr::local_tempdir()

  # Create R/auto directory with a file
  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "my_data <- mtcars",
      "analyze <- function(my_data) summary(my_data)"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  # Create targets directory
  dir.create(file.path(tmp_dir, "targets"))

  # Generate targets
  generate_targets(path = tmp_dir)

  # Check output file exists
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_true(file.exists(output_file))

  # Check content
  content <- readLines(output_file)
  expect_true(any(grepl("AUTOGENERATED", content)))
  expect_true(any(grepl("tar_target\\(analyze", content)))
  expect_true(any(grepl("tar_target\\(my_data", content)))
})

test_that("generate_targets with write=FALSE returns lines without writing", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines("x <- 1", file.path(auto_dir, "test.R"))

  result <- generate_targets(path = tmp_dir, write = FALSE)

  expect_type(result, "character")
  expect_true(any(grepl("tar_target", result)))

  # File should not exist
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_false(file.exists(output_file))
})
