test_that("make_function_target generates function and result targets", {
  # Function with args
  result <- make_function_target("my_func", list(x = NULL, y = NULL))
  expect_length(result, 2)
  expect_equal(result[1], '  tar_target(my_func_fn, get("my_func", envir = globalenv()))')
  expect_equal(result[2], "  tar_target(my_func, my_func_fn(x, y))")

  # Function with no args
  result <- make_function_target("no_args", list())
  expect_length(result, 2)
  expect_equal(result[1], '  tar_target(no_args_fn, get("no_args", envir = globalenv()))')
  expect_equal(result[2], "  tar_target(no_args, no_args_fn())")
})

test_that("make_constant_target generates correct output", {
  result <- make_constant_target("my_const")
  expect_equal(result, "  tar_target(my_const, my_const)")
})

test_that("generate_targets creates output file", {
  tmp_dir <- withr::local_tempdir()

  # Create R/auto directory with a file
  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "my_data <- mtcars",
      "analyze <- function(my_data) summary(my_data)"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  # Create targets directory
  dir.create(file.path(tmp_dir, "targets"))

  # Generate targets
  generate_targets(path = tmp_dir)

  # Check output file exists
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_true(file.exists(output_file))

  # Check content
  content <- readLines(output_file)
  expect_true(any(grepl("AUTOGENERATED", content)))
  expect_true(any(grepl('tar_target\\(analyze_fn, get\\("analyze"', content)))
  expect_true(any(grepl("tar_target\\(analyze,", content)))
  expect_true(any(grepl("tar_target\\(my_data", content)))
})

test_that("generate_targets with write=FALSE returns lines without writing", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines("x <- 1", file.path(auto_dir, "test.R"))

  result <- generate_targets(path = tmp_dir, write = FALSE)

  expect_type(result, "character")
  expect_true(any(grepl("tar_target", result)))

  # File should not exist
  output_file <- file.path(tmp_dir, "targets", "_targets_generated.R")
  expect_false(file.exists(output_file))
})

test_that("function targets create _fn suffix for function object tracking", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "data <- 1:10",
      "process <- function(data) data * 2"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # Should have _fn suffix for function (using get() to avoid cycles)
  expect_true(any(grepl('tar_target\\(process_fn, get\\("process"', result)))

  # Result target should call _fn version
  expect_true(any(grepl("tar_target\\(process, process_fn\\(data\\)\\)", result)))

  # Constants should not have _fn suffix
  expect_true(any(grepl("tar_target\\(data, data\\)", result)))
  expect_false(any(grepl("data_fn", result)))
})

test_that("constants evaluate their value directly for change detection", {
  # Constants don't need _fn_ pattern because tar_target(const, const)
  # evaluates to the actual value, which targets hashes.
  # If the constant's value changes, the hash changes and target is invalidated.
  result <- make_constant_target("params")
  expect_equal(result, "  tar_target(params, params)")

  # This is different from functions where the body is encapsulated
  # and not visible in the call expression
})

test_that("file targets are detected by _file suffix", {
  expect_true(is_file_target("raw_data_file"))
  expect_true(is_file_target("output_file"))
  expect_false(is_file_target("data"))
  expect_false(is_file_target("threshold"))
})

test_that("make_file_target adds format = 'file'", {
  result <- make_file_target("raw_data_file")
  expect_equal(result, "  tar_target(raw_data_file, raw_data_file, format = \"file\")")
})

test_that("function targets with _file suffix get format = 'file'", {
  # Function returning a file path should have format = "file" on result target
  result <- make_function_target("output_file", list(data = NULL))
  expect_length(result, 2)
  expect_equal(result[1], '  tar_target(output_file_fn, get("output_file", envir = globalenv()))')
  expect_equal(result[2], '  tar_target(output_file, output_file_fn(data), format = "file")')
})

test_that("generate_targets handles file targets for constants and functions", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "raw_data_file <- \"data/input.csv\"",
      "threshold <- 0.05",
      "output_file <- function(data) {",
      "  write.csv(data, \"output.csv\")",
      "  \"output.csv\"",
      "}",
      "process <- function(raw_data_file) read.csv(raw_data_file)"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # Constant file target
  expect_true(any(grepl('tar_target\\(raw_data_file, raw_data_file, format = "file"\\)', result)))

  # Regular constant (no format)
  expect_true(any(grepl('tar_target\\(threshold, threshold\\)', result)))

  # Function file target (result has format = "file", fn uses get())
  expect_true(any(grepl('tar_target\\(output_file_fn, get\\("output_file"', result)))
  expect_true(any(grepl('tar_target\\(output_file, output_file_fn\\(data\\), format = "file"\\)', result)))

  # Regular function (fn uses get())
  expect_true(any(grepl('tar_target\\(process_fn, get\\("process"', result)))
  expect_true(any(grepl('tar_target\\(process, process_fn\\(raw_data_file\\)\\)', result)))
})

test_that("generated target names are valid R identifiers", {
  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "process <- function(data) data * 2"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # All generated code should parse without error
  expect_error(parse(text = result), NA)

  # Extract target names and verify they're valid R identifiers
  target_names <- gsub(".*tar_target\\(([^,]+),.*", "\\1", result[grep("tar_target", result)])
  target_names <- trimws(target_names)

  for (name in target_names) {
    # Should not start with a dot (targets requirement)
    expect_false(grepl("^\\.", name), info = paste("Name starts with dot:", name))
    # Should not start with underscore (R syntax error)
    expect_false(grepl("^_", name), info = paste("Name starts with underscore:", name))
    # Should be a valid R identifier
    expect_true(make.names(name) == name, info = paste("Invalid R identifier:", name))
  }
})

test_that("generated targets can be validated by targets package", {
  skip_if_not_installed("targets")

  tmp_dir <- withr::local_tempdir()

  auto_dir <- file.path(tmp_dir, "R", "auto")
  dir.create(auto_dir, recursive = TRUE)
  writeLines(
    c(
      "data <- 1:10",
      "process <- function(data) data * 2"
    ),
    file.path(auto_dir, "pipeline.R")
  )

  result <- generate_targets(path = tmp_dir, write = FALSE)

  # Create a valid targets list (using targets::tar_target explicitly)
  code <- paste0("list(\n", paste(result, collapse = ",\n"), "\n)")
  targets_list <- eval(parse(text = code), envir = asNamespace("targets"))

  # Check that target names are valid for targets package
  for (target in targets_list) {
    # targets requires names that don't start with dot
    expect_false(
      grepl("^\\.", target$settings$name),
      info = paste("Target name starts with dot:", target$settings$name)
    )
  }
})
