#' Check if expression is a function definition
#'
#' @param expr An R expression
#' @return Logical indicating if expression is a function definition
#' @keywords internal
is_function_def <- function(expr) {
  if (!is.call(expr)) {
    return(FALSE)
  }
  op <- as.character(expr[[1]])
  if (!(op %in% c("<-", "="))) {
    return(FALSE)
  }
  if (length(expr) < 3) {
    return(FALSE)
  }
  is.call(expr[[3]]) && identical(expr[[3]][[1]], as.name("function"))
}

#' Check if expression is a constant (non-function assignment)
#'
#' @param expr An R expression
#' @return Logical indicating if expression is a constant assignment
#' @keywords internal
is_constant_def <- function(expr) {
  if (!is.call(expr)) {
    return(FALSE)
  }
  op <- as.character(expr[[1]])
  if (!(op %in% c("<-", "="))) {
    return(FALSE)
  }
  if (length(expr) < 3) {
    return(FALSE)
  }
  # It's a constant if it's an assignment but NOT a function definition
  !is_function_def(expr)
}

#' Get the name from an assignment expression
#'
#' @param expr An assignment expression
#' @return Character string with the assigned name
#' @keywords internal
get_assignment_name <- function(expr) {
  as.character(expr[[2]])
}

#' Get formals from a function definition expression
#'
#' @param expr A function definition expression
#' @return List of formal arguments (or NULL if not a function)
#' @keywords internal
get_function_formals <- function(expr) {
  if (!is_function_def(expr)) {
    return(NULL)
  }
  func_expr <- expr[[3]]
  # func_expr is function(args) body
  # formals are in func_expr[[2]]
  as.list(func_expr[[2]])
}

#' Generate tar_target call string for a function
#'
#' @param name Function name
#' @param formals List of formal arguments
#' @return Character string with tar_target() call
#' @keywords internal
make_function_target <- function(name, formals) {
  arg_names <- names(formals)
  if (is.null(arg_names) || length(arg_names) == 0) {
    call_str <- paste0(name, "()")
  } else {
    call_str <- paste0(name, "(", paste(arg_names, collapse = ", "), ")")
  }
  paste0("  tar_target(", name, ", ", call_str, ")")
}

#' Generate tar_target call string for a constant
#'
#' @param name Constant name
#' @return Character string with tar_target() call
#' @keywords internal
make_constant_target <- function(name) {
  paste0("  tar_target(", name, ", ", name, ")")
}

#' Write generated targets file with header
#'
#' @param target_lines Character vector of tar_target() call strings
#' @param path Output file path
#' @param source_dir Source directory that was scanned
#' @keywords internal
write_targets_file <- function(target_lines, path, source_dir = "R/auto/") {
  header <- c(
    "# AUTOGENERATED by autotargets - DO NOT EDIT BY HAND",
    paste0("# Generated: ", Sys.time()),
    paste0("# Source: ", source_dir),
    "",
    "list(",
    ""
  )

  footer <- c(
    ")"
  )

  # Add commas between targets
  if (length(target_lines) > 0) {
    target_lines[-length(target_lines)] <- paste0(
      target_lines[-length(target_lines)],
      ","
    )
  }

  content <- c(header, target_lines, footer)

  # Ensure directory exists
  fs::dir_create(fs::path_dir(path))

  writeLines(content, path)
  cli::cli_alert_success(
    "Generated {length(target_lines)} target(s) in {.file {path}}"
  )

  invisible(path)
}
